// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Clone: typeof import('./components/clone.vue')['default']
    CloneOnControl: typeof import('./components/clone-on-control.vue')['default']
    CustomClone: typeof import('./components/custom-clone.vue')['default']
    Footerslot: typeof import('./components/footerslot.vue')['default']
    Handle: typeof import('./components/handle.vue')['default']
    Headerslot: typeof import('./components/headerslot.vue')['default']
    Nested: typeof import('./components/infra/nested.vue')['default']
    NestedExample: typeof import('./components/nested-example.vue')['default']
    NestedTest: typeof import('./components/nested/nested-test.vue')['default']
    RawDisplayer: typeof import('./components/infra/raw-displayer.vue')['default']
    Simple: typeof import('./components/simple.vue')['default']
    TableColumnExample: typeof import('./components/table-column-example.vue')['default']
    TableExample: typeof import('./components/table-example.vue')['default']
    ThirdParty: typeof import('./components/third-party.vue')['default']
    TransitionExample: typeof import('./components/transition-example.vue')['default']
    TransitionExample2: typeof import('./components/transition-example-2.vue')['default']
    TwoListHeaderslots: typeof import('./components/two-list-headerslots.vue')['default']
    TwoLists: typeof import('./components/two-lists.vue')['default']
  }
}

export { }
